[package]
name = "edi-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
regex = "1.0"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
serde_support = ["serde"]

[dev-dependencies]
assert_matches = "1.5"